language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
before_install:
  - pip install pytest-cov
  - pip install coveralls
install:
  - pip install .
script:
  - py.test --cov=assertpy
after_success:
  - coveralls
sudo: false
